name: '이슈 생성'
description: 'Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다.'
labels: []
title: 'CUL-이슈번호: 이슈 이름을 작성해주세요'
body:
  - type: input
    id: parentKey
    attributes:
      label: '🎟️ 상위 작업 (Ticket Number)'
      description: '상위 작업의 Ticket Number를 기입해주세요 (예: CUL-00)'
      placeholder: 'CUL-00'
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: '🌳 브랜치명 (Branch)'
      description: '영어로 브랜치명을 작성해주세요 (예: feature/CUL-00-description)'
      placeholder: 'feature/CUL-00-description'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: '📝 상세 내용 (Description)'
      description: '이슈에 대해서 간략히 설명해주세요'
      placeholder: '이슈에 대한 상세 내용을 입력해주세요'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '✅ 체크리스트 (Tasks)'
      description: '해당 이슈에 대해 필요한 작업 목록을 작성해주세요'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true

  - type: dropdown
    id: label
    attributes:
      label: '🏷️ 라벨 (Label)'
      description: '이슈 성격에 맞는 라벨을 선택해주세요'
      options:
        - feat
        - fix
        - chore
        - refactor
        - docs
    validations:
      required: true
