name: '이슈 생성'
description: 'Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다.'
labels: []
title: '이슈 이름을 작성해주세요'

body:
  - type: input
    id: parentKey
    attributes:
      label: '🎟️ 상위 작업 (Ticket Number)'
      description: '상위 작업의 Ticket Number를 기입해주세요 (예: CUL-00)'
      placeholder: 'CUL-00'
    validations:
      required: true

  - type: input
    id: branchName
    attributes:
      label: '🌿 브랜치 이름'
      description: '브랜치 이름을 기입해주세요 (예: feat/login)'
      placeholder: 'feat/login'
    validations:
      required: true

  - type: dropdown
    id: issuetype
    attributes:
      label: '📌 이슈 타입 (Issue Type)'
      description: 'Jira에 생성할 이슈의 타입을 선택해주세요'
      options:
        - 'Task'
        - 'Bug'
        - 'Story'
        - 'Subtask'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: '📝 상세 내용 (Description)'
      description: '이슈에 대해서 간략히 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '✅ 체크리스트 (Tasks)'
      description: '해당 이슈에 대해 필요한 작업 목록을 작성해주세요'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true

  - type: dropdown
    id: createBranch
    attributes:
      label: '🌿 브랜치 생성 여부'
      description: '이 이슈에 대해 브랜치를 생성할지 선택해주세요'
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true

  - type: dropdown
    id: label
    attributes:
      label: '🏷️ 라벨 (Label)'
      description: '이슈 성격에 맞는 라벨을 선택해주세요'
      options:
        - 'feat'
        - 'fix'
        - 'chore'
        - 'refactor'
        - 'docs'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ℹ️ 브랜치명은 Jira 이슈 생성 후 자동으로 `feature/이슈번호-이슈제목` 형식으로 생성됩니다.

